#!/bin/bash
# This script runs the GZoltar jar file, the arguments are defined as below
# java -jar com.gzoltar-0.0.10-jar-with-dependencies.jar <project directory> <packages to instrument or test packages to execute (separated by ',')> <class path: bin/target directory, librabries, etc (separated by ':')>
# $1 command line argument corresponds to project directory
# $2 command line argument corresponds to packages to instrument
# $3 command line argument corresponds class path

java -jar ../../lib/com.gzoltar-0.0.11-jar-with-dependencies.jar $1 $2 $3 

