#!/bin/bash
# This script runs tacoco and creates the neccessary files in both the 
# System-under-test dir and the tacoco dir, this is a copy of the run-tacoco
# script already found in the tacoco dir, placed with the other scripts for 
# convenience since changes cannot be made to the tacoco repo without permission

# (Note: there are no ending forward slashes at the end of the paths)
# the command line arg are as follows:
# $1 - absolute class path of the dir under test
# $2 - absolute class path of the tacoco dir

# example: ./run-tacoco absolute/path/of/your/project/root absolute/path/of/tacoco/root

cd $1
mvn dependency:build-classpath -Dmdep.outputFile="cp.txt"
export CLASSPATH=`cat cp.txt`:$CLASSPATH
echo $CLASSPATH
export CLASSPATH=$1/target/test-classes:$1/target/classes:$CLASSPATH
echo $CLASSPATH

cd $2
mvn dependency:build-classpath -Dmdep.outputFile="cp.txt"
export CLASSPATH=`cat cp.txt`:$CLASSPATH
echo $CLASSPATH
export CLASSPATH=$2/target/test-classes:$2/target/classes:$CLASSPATH
echo $CLASSPATH
mvn dependency:copy-dependencies -DoutputDirectory=lib
java -javaagent:lib/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=jacoco.exec,dumponexit=false org.spideruci.tacoco.TacocoRunner $1/target/test-classes

